//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190410_BlogV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makaleler
    {
        public int MakalelerID { get; set; }
        public string Baslık { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<int> GoruntulenmeSayisi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public Nullable<int> BegenSayisi { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
